version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:8000"
    volumes:
      - .:/app
    environment:
      # Supabase connection pooler settings
      - SUPABASE_DB_USER=${SUPABASE_DB_USER}
      - SUPABASE_PASSWORD=${SUPABASE_PASSWORD}
      - SUPABASE_DB_HOST=${SUPABASE_DB_HOST}
      - SUPABASE_DB_PORT=${SUPABASE_DB_PORT}
      - SUPABASE_DB_NAME=${SUPABASE_DB_NAME}
      # API keys and auth
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - XAI_API_KEY=${XAI_API_KEY}
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_API_AUDIENCE=${AUTH0_API_AUDIENCE}
      - AUTH0_ALGORITHMS=${AUTH0_ALGORITHMS}
      # Application settings
      - APP_ENV=${APP_ENV}
      - DEBUG=${DEBUG}
    networks:
      - writers-llm-network

networks:
  writers-llm-network:
    driver: bridge