version: '3.8'

services:
  server:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/app
    environment:
      # Supabase connection pooler settings
      - SUPABASE_DB_USER=${SUPABASE_DB_USER}
      - SUPABASE_DB_PASSWORD=${SUPABASE_DB_PASSWORD}
      - SUPABASE_DB_HOST=${SUPABASE_DB_HOST}
      - SUPABASE_DB_PORT=${SUPABASE_DB_PORT}
      - SUPABASE_DB_NAME=${SUPABASE_DB_NAME}
      # API keys and auth
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - XAI_API_KEY=${XAI_API_KEY}
      - PORTKEY_API_KEY=${PORTKEY_API_KEY}
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_API_AUDIENCE=${AUTH0_API_AUDIENCE}
      - AUTH0_ALGORITHMS=${AUTH0_ALGORITHMS}
      # Application settings
      - ENV=${ENV}
      # Redis connection
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    networks:
      - ecs-vaani-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - ecs-vaani-network

  rq-worker:
    build: .
    command: ["/bin/bash", "worker-init.sh"]
    volumes:
      - .:/app
    environment:
      # Supabase connection pooler settings
      - SUPABASE_DB_USER=${SUPABASE_DB_USER}
      - SUPABASE_DB_PASSWORD=${SUPABASE_DB_PASSWORD}
      - SUPABASE_DB_HOST=${SUPABASE_DB_HOST}
      - SUPABASE_DB_PORT=${SUPABASE_DB_PORT}
      - SUPABASE_DB_NAME=${SUPABASE_DB_NAME}
      # API keys and auth
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - XAI_API_KEY=${XAI_API_KEY}
      - PORTKEY_API_KEY=${PORTKEY_API_KEY}
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_API_AUDIENCE=${AUTH0_API_AUDIENCE}
      - AUTH0_ALGORITHMS=${AUTH0_ALGORITHMS}
      # Application settings
      - ENV=${ENV}
      # Redis connection
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - ecs-vaani-network

volumes:
  redis-data:

networks:
  ecs-vaani-network:
    driver: bridge
