# Sample YAML configuration for demonstration
application:
  name: Writers LLM Backend
  version: 1.0.0
  description: Backend service for a writer's tool that leverages LLMs

database:
  host: localhost
  port: 5432
  name: writers_db
  username: postgres
  connection_timeout: 30

ai_settings:
  default_model: gpt-4o
  models:
    - name: gpt-4o
      temperature: 0.7
      max_tokens: 4096
    - name: gpt-3.5-turbo
      temperature: 0.8
      max_tokens: 2048
  
  endpoints:
    plot_analysis:
      model: gpt-4o
      temperature: 0.5
    chapter_generation:
      model: gpt-4o
      temperature: 0.7
    character_development:
      model: gpt-4o
      temperature: 0.6

features:
  - plot_analyzer
  - chapter_generator
  - story_abstractor
  - markdown_viewer

logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: logs/application.log
