from enum import Enum

class StoryboardStatus(Enum):
    NOT_STARTED = "NOT_STARTED"
    CHARACTER_ARC_GENERATION_IN_PROGRESS = "CHARACTER_ARC_GENERATION_IN_PROGRESS"
    CHARACTER_ARC_GENERATION_COMPLETED = "CHARACTER_ARC_GENERATION_COMPLETED"
    PLOT_BEATS_GENERATION_IN_PROGRESS = "PLOT_BEATS_GENERATION_IN_PROGRESS"
    PLOT_BEATS_GENERATION_COMPLETED = "PLOT_BEATS_GENERATION_COMPLETED"
    
class PromptSource(Enum):
    SCENE = "SCENE"
    CHAPTER = "CHAPTER"